import { Router } from 'express';
import userRoutes from '@modules/user/routes/user_routes';
import subscriptionRoutes from '@modules/subscriptions/routes/subscription_routes';
import faqRoutes from '@modules/faqs/routes/faq_routes';
import contactusRoutes from '@modules/user/partial/contact/routes/contact_routes';
import settingRoutes from '@modules/setting/routes/setting_routes';
import termRoutes from '@modules/setting/partial/terms/routes/terms_routes';
import privacyRoutes from '@modules/setting/partial/privacy/routes/privacy_routes';
import seoRoutes from '@modules/seo/routes/seo_routes';
import breadCrumRoutes from '@modules/breadcrumb/routes/breadcrumb_routes';
import teamRoutes from '@modules/team/routes/team_routes';
import blogRoutes from '@modules/blog/routes/blog_routes';
import homeRoutes from '@modules/home/routes/home_routes';
import accreditationRoutes from '@modules/accreditation/routes/accreditation_routes';
import missionVisionRoutes from '@modules/home/partial/missionVision/routes/vision_mission_routes';
import patnerRoutes from '@modules/ourpatner/routes/ourpatner_routes';
import aboutUsRoutes from '@modules/aboutus/routes/about_us_routes';
import homeSectionRoutes from '@modules/home/partial/homeSection/routes/home_section_routes';
import historyRoutes from '@modules/aboutus/partial/history/routes/history_routes';
import backgroundRoutes from '@modules/aboutus/partial/background/routes/background_routes';
import objectivesRoutes from '@modules/aboutus/partial/objectives/routes/objectives_routes';
import comitteeMemberRoutes from '@modules/members/routes/member_routes';
import presidentRoutes from '@modules/president/routes/president_routes';
import noticeRoutes from '@modules/notice/routes/notice_routes';

const router = Router();

router.use('/user', userRoutes);
router.use('/subscription', subscriptionRoutes);
router.use('/faq', faqRoutes);
router.use('/contact-us', contactusRoutes);
router.use('/setting', settingRoutes);
router.use('/term', termRoutes);
router.use('/privacy', privacyRoutes);
router.use('/seo', seoRoutes);
router.use('/breadcrumb', breadCrumRoutes);
router.use('/team', teamRoutes);
router.use('/blog', blogRoutes);
router.use('/home', homeRoutes);
router.use('/accreditation', accreditationRoutes);
router.use('/mission-vision', missionVisionRoutes);
router.use('/our-patner', patnerRoutes);
router.use('/about-us', aboutUsRoutes);
router.use('/home-section', homeSectionRoutes);
router.use('/history', historyRoutes);
router.use('/background', backgroundRoutes);
router.use('/objectives', objectivesRoutes);
router.use('/committee-member', comitteeMemberRoutes);
router.use('/president', presidentRoutes);
router.use('/notice', noticeRoutes);

export default router;
